name: Release TBD

on:
  release:
    types:
      - published
jobs:
  call-reusable-workflow:
    name: Release fix
    if: github.actor != 'gluon-app[bot]'
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/python-release-tbd.yml@v1
    with:
      technology: 'python'
    secrets: inherit
