name: Python version release validation
on:
  pull_request:
    branches:
      - development
      - develop
      - main
      - master
      - release-v[0-9]+.[0-9]+.[xX]
##      - feat/ci-granular-concurrency
##      - feat/metrics-observability
##      - test/ci-lab
    paths-ignore:
      - 'docs/**'
concurrency:
  group: version-val-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  call-reusable-workflow:
    name: Version release validation
    uses: santander-group-shared-assets/gln-workflows/.github/workflows/version-release-validation.yml@v1
    with:
      version_file: 'setup.py'
    secrets: inherit
