swagger: '2.0'
info:
  title: Test
  version: 1.0.0-SNAPSHOT
  description: Example used in training video. Managing descriptions.
               - Extending dictionary descriptions
               - Overwriting descriptions in referenced objects
schemes:
  - https
basePath: /tests/
tags:
  - name: tests
    description: Tests
consumes:
  - application/json
produces:
  - application/json
paths:
  '/test1/{test_id}':
    get:
      description: |
        Validating objects.
      produces:
        - application/json
      parameters:
        - name: test_id
          type: string
          required: true
          in: path
          description: test identifier
          x-example: 20210729-001
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Account'
          headers: {}

definitions:

   Account :
    type : "object"
#The base description can be extended
    description : "Data structure containing information about an account. TEXT COMPLEMENTING THE DICIONARY DESCRIPTION"
    properties :
       accountId :
#The base description can be extended
          description : "Account number, in the format defined in 'accountIdType'.  TEXT COMPLEMENTING THE DICIONARY DESCRIPTION"
          type : "string"
          example : 4.916553001234567E17
       country :
#The generic description of the Country object can be overwritten (using replacement)
          description : "Data structure containing country details. If the value of 'accountIdType' is 'BBAN', this data structure is mandatory."
          type : "object"
          properties :
            code :
                type : "string"
                description : "Country code. The value is based on the ISO 3166 (https://www.iso.org/obp/ui/#search/code/)."
                example : "US"
                maxLength : 3
            name :
                type : "string"
                description : "Country name. The value is based on the ISO 3166 (https://www.iso.org/obp/ui/#search/code/)."
                example : "United States of America"
                minLength : 0
                maxLength : 35